title: Anjana R Azhuvath
#logo:/assets/img/headshot.png
Description: Economics graduate adept in deploying R & Python for financial analysis, predictive modeling, forecasting and risk mitigation. 
Seasoned in steering data-oriented teams and conveying analytical insights to stakeholders.
Leverages the computational acumen to construct quantitative frameworks, synthesizing complex data into actionable intelligence for driving strategic decision-making. 
Well-versed in distilling technical specifics into accessible directives across corporate hierarchies.
show_downloads: true
theme: jekyll-theme-minimal


